package com.nickmous.beanstash.integration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nickmous.beanstash.configuration.TestcontainersConfig;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.web.servlet.MockMvc;

/**
 * Exports the live OpenAPI specification (generated by springdoc from the
 * controllers) to {@code backend/openapi.json}. Running the test suite keeps
 * that committed spec in sync with the code; the openapi-generator plugin then
 * turns the spec into the frontend TypeScript client.
 *
 * <p>If this rewrites {@code openapi.json}, the API surface changed: commit the
 * updated spec and regenerate the client (see README).</p>
 */
@SpringBootTest
@Import(TestcontainersConfig.class)
@ContextConfiguration(initializers = TestcontainersConfig.Initializer.class)
@ActiveProfiles("test")
@AutoConfigureMockMvc
public class OpenApiDocsExportTests {

    private static final Path SPEC_PATH = Path.of(System.getProperty("user.dir"), "openapi.json");

    @Autowired
    private MockMvc mockMvc;

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    void exportsOpenApiSpecToFile() throws Exception {
        String body = mockMvc.perform(get("/v3/api-docs"))
            .andExpect(status().isOk())
            .andReturn()
            .getResponse()
            .getContentAsString();

        JsonNode spec = objectMapper.readTree(body);

        assertThat(spec.path("openapi").asText()).startsWith("3.");
        // Auth endpoints now sit under the versioned prefix (e.g. /api/{version}/auth/login),
        // so match by suffix rather than the old unversioned literal.
        boolean hasAuthLogin = false;
        java.util.Iterator<String> pathNames = spec.path("paths").fieldNames();
        while (pathNames.hasNext()) {
            if (pathNames.next().endsWith("/auth/login")) {
                hasAuthLogin = true;
                break;
            }
        }
        assertThat(hasAuthLogin).isTrue();

        String pretty = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(spec);
        Files.writeString(SPEC_PATH, pretty + System.lineSeparator());
    }
}
