# Production secrets — fill in values before deploying
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:OvGnr6ApzdFfZHvOpcJgun1D2amRCMB+PA4XYJY4IkGNSpG2Dy+lxMXYDJe3Pal/cMEX,iv:dLz+Zh+6fL8sBFkvh8Lzkify4IkFLLrpzzzye1d6k4o=,tag:G4fDGRKYGPrCSj0A/WWVIQ==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:aXiUuiCuGrCU,iv:KXahTPMgm9XuEF8t4FVsAcJfRKw4DPVuWa3PaFYVnqU=,tag:u3KK7q/MW4xkW+ZEAoG1Gg==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:GYaDJDLNaL9A/4Q54wbHffUQ2DHG0DGO6j8HlT3q,iv:Gk7AiYkdxbON0hGO3l1zcer1BNPKW/ai1R8DSrw95WI=,tag:t1dhIe6TuOnqQFk5REUgZw==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:JHgaiUDIIdvEVbAGixvonqHWYAsqirFru6OcoCNgslv91oUTrDDsdPd7249WDb0MBzsQiA5ZKc5WVXXCUg==,iv:nG1P/FZJ3uLKpYwgRlBYtgaoYTrVdTntMdJsX9xi24U=,tag:4Kf5H0F/aGu3FA9yvUSfmw==,type:str]
    NEXT_PUBLIC_SENTRY_DSN: ENC[AES256_GCM,data:VbWrmRQGFs28L1JwZAf49Ex5tZOkICNKnLE0Jo4mNIZBVsGGgD4QvknbBZPQtgaNfW1oJ11I0Sgo73KynA==,iv:JrvZWkXGMsy4HFdoB7nA9q3LQNyyI4IA63krLTo66hU=,tag:EG2XfTvRNK5tGuaRcyB4iw==,type:str]
sops:
    lastmodified: "2026-03-01T11:14:02Z"
    mac: ENC[AES256_GCM,data:XSm3hWxXuGqhrBe96bGnhCpiB/TJmA1EKzaQPYsMpqKk7x8bBjf6pJGTtewzkb8ujfIdaQSVvnNk4WCxlIP4D8+8XZa6vXWo3n2viR39r2TFVOB29mWUNFYELtQpbOHLTah3I8v6fl0Jmq2OMCR+Xr5mKeB7fY8L24sFmZoSiMQ=,iv:Kgv0xJse15LFEfejzVdl7DN9tCMqIsByN2/euR+vcUU=,tag:YYQmp05vY/MyH2qYpntm+w==,type:str]
    pgp:
        - created_at: "2026-03-01T10:48:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAqPpPkL60znAsfCqKDvp5OKUesweZ3ufbFDQMJUoQzZ/G
            8sxuAlTDqvl9SuQSObQ+D3rUOszC71/XI3LyHpkki5dDhXgfO+yUjcSYXUlwL56F
            oxWpwuVDMlt5EHkHhPyZ0ItZ6ItTGlEDtfgRZYelaaH7PDIUP2GFGWuRy9XXP3Br
            tcOlrHvyK1kCtSJVolCjz6j0SEjZF5fXm7n/XgRmbAPfGY8V9UZjmeTjSfmG3gEQ
            /p4HoZONuioJ7jftvw7YmulseJcl1P3CVtuIY9MwQPFVtlSXYV15yFKFlT4u3y3L
            CEfE6gxF8UBVaNB4hwBtAcP8vHeguR69S1BTc7qeab3b6qPZf8uzCma2dtvBYKXk
            bd5hWPtJDMGS9iMK9Ffa8YkciCkgdyLFQaXeoC+dNu4Cxe0PWKJesJ6NnQvNpfWA
            Kc7ER5Ejdam2yAPt/mQQ4L7sW3GwBwiqGV+nA1oYmTt89bmzIBcffGIfYbEgJSCO
            zAoyQhG+nzWuV9TNIxIIogWZMzGypy52Nqkl9iZlqlkxTN6LEwbZkDvluAmmriUo
            dNhQdZmUkZ6HEcS3wEkpXZ6BP3oD+xbNVli8Q1egzhWLSgIlQU0yh4BROx8jzzNW
            Tc8da0qc/cKwTguVh0/xzUC61UCA0YLbgeB+VMPBvO0GRUEViCcAY2AehfHnZhnU
            aAEJAhC7P01U3y2LGUOMq5R1+K8AtMGvuoWLBh0ZlVFqs34Ur82ITOom/u9riHDg
            SOo+JtvG5YDssa6H/VaaR9W1J0YE9GR3vciaZ4dUPtZ/ENDruaVKlBX5rVOyNPhh
            7BRFDEFpTkR/
            =c9UY
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:XXVvx6nVPVxX,iv:cTu+VsZJK4wsBLnFRSy60ky1/f3qoLQhhqQWNpjFCH8=,tag:C3Qn4MYlR5SMViRQhIzAWQ==,type:str]
    password: ENC[AES256_GCM,data:fq+K9hj1dXb+LmoSuN77tOreD9F5GQj5XoYilCvF,iv:K5BHleOpN12KsCCT1jM6c4boZyydgLPlCvmI1iBvs8Y=,tag:Jm1aVTdbnligZytVVQ2/Nw==,type:str]
sops:
    lastmodified: "2026-03-01T11:14:02Z"
    mac: ENC[AES256_GCM,data:XSm3hWxXuGqhrBe96bGnhCpiB/TJmA1EKzaQPYsMpqKk7x8bBjf6pJGTtewzkb8ujfIdaQSVvnNk4WCxlIP4D8+8XZa6vXWo3n2viR39r2TFVOB29mWUNFYELtQpbOHLTah3I8v6fl0Jmq2OMCR+Xr5mKeB7fY8L24sFmZoSiMQ=,iv:Kgv0xJse15LFEfejzVdl7DN9tCMqIsByN2/euR+vcUU=,tag:YYQmp05vY/MyH2qYpntm+w==,type:str]
    pgp:
        - created_at: "2026-03-01T10:48:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWARAAqPpPkL60znAsfCqKDvp5OKUesweZ3ufbFDQMJUoQzZ/G
            8sxuAlTDqvl9SuQSObQ+D3rUOszC71/XI3LyHpkki5dDhXgfO+yUjcSYXUlwL56F
            oxWpwuVDMlt5EHkHhPyZ0ItZ6ItTGlEDtfgRZYelaaH7PDIUP2GFGWuRy9XXP3Br
            tcOlrHvyK1kCtSJVolCjz6j0SEjZF5fXm7n/XgRmbAPfGY8V9UZjmeTjSfmG3gEQ
            /p4HoZONuioJ7jftvw7YmulseJcl1P3CVtuIY9MwQPFVtlSXYV15yFKFlT4u3y3L
            CEfE6gxF8UBVaNB4hwBtAcP8vHeguR69S1BTc7qeab3b6qPZf8uzCma2dtvBYKXk
            bd5hWPtJDMGS9iMK9Ffa8YkciCkgdyLFQaXeoC+dNu4Cxe0PWKJesJ6NnQvNpfWA
            Kc7ER5Ejdam2yAPt/mQQ4L7sW3GwBwiqGV+nA1oYmTt89bmzIBcffGIfYbEgJSCO
            zAoyQhG+nzWuV9TNIxIIogWZMzGypy52Nqkl9iZlqlkxTN6LEwbZkDvluAmmriUo
            dNhQdZmUkZ6HEcS3wEkpXZ6BP3oD+xbNVli8Q1egzhWLSgIlQU0yh4BROx8jzzNW
            Tc8da0qc/cKwTguVh0/xzUC61UCA0YLbgeB+VMPBvO0GRUEViCcAY2AehfHnZhnU
            aAEJAhC7P01U3y2LGUOMq5R1+K8AtMGvuoWLBh0ZlVFqs34Ur82ITOom/u9riHDg
            SOo+JtvG5YDssa6H/VaaR9W1J0YE9GR3vciaZ4dUPtZ/ENDruaVKlBX5rVOyNPhh
            7BRFDEFpTkR/
            =c9UY
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
