# Staging secrets — fill in values before deploying
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:qq4M21GdlfVmhW60FpWKXXczdCgURsVbNlN1MpaQXvU2eglbQhc7h4AOcpASequFUM91,iv:JfWt/Y+X2Y8hqcX/AqBn7SqN2ZTB/4l+6HSL6QNJp9Q=,tag:JvUdpinhR8K8Ax4VjuJiAg==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:oEQE9coJY7A4,iv:IyCf5p5I51bkGVmdW6u2aFtOg/G4IduMESUGXvQJaHM=,tag:+oo01fPvalM85mFI1ukmfQ==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:4EyfcgJ00P+vsgYBviqd9Jg9NYCGkWdIA+Fux+Jp,iv:gNWJK0zQ8y7jnzXSVrG8Cut7HPi5UzNhIpo79TgntjY=,tag:4Alr7NKRKjgSfWO8tQ920w==,type:str]
    BASIC_AUTH_USER: ENC[AES256_GCM,data:TCkKHo9vctHh,iv:OuFQdhjkFx0M5PAmwEK8CBO1+JQt9LyOlsRBylCUP1I=,tag:OroPIdLPG2Msl1mM2WaL3g==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:TjFeBHGHfev2iA==,iv:gXwffmRBrV+qPR8sExlQ7lXfINln06pWzJEwiISEAn8=,tag:+8GuZ5oWUYok5vrCbiIWkA==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:+AE701qwy4sgz4JQs6Qj2HNUDcVsDPLmPLx/h0MY/xigTa5UXHfSSRJHP9KpEQVOMN93bwBdcaD/5cI3Zw==,iv:O5wM2KL/dIkji4k0qnzwFrHfXbYJMmPzVu0MUs1/GtY=,tag:H76VFbNFlz4+r0n0YkRifA==,type:str]
sops:
    lastmodified: "2026-03-01T10:48:07Z"
    mac: ENC[AES256_GCM,data:+vgm2cTZN3eipcnKNKoDdZsB3fJfi/9ddbHI75y2vDPPeFP2KcBRrrFAAlej6c8lGqC1pNqW7c1peMLVZ1DZLlGoSVlq2zck2gc3F7gXFfBFMJKTThjGQ8tyvY1gc2ZqqFb5K3AIav3EchDJeEns8nfE+KwNfLKoFt3VRTZu1Xw=,iv:HMSyDZHzSg3tkroTCu8m+GdxIkiuPPRI/K2eYHYMtA8=,tag:IcQ4N1ynbhnbTHRfwSrfSw==,type:str]
    pgp:
        - created_at: "2026-03-01T10:48:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWAQ//TZ4oKy9W4uH93Vm1xZT8RkK9ZfvcRb3z0SXXAlbiqSvg
            /FOy9JBJEtOVLdN1CgYDqrX/UsnXWwf6bXJnQxjL9aFimElOOyIgrWF5pnR/T2KL
            xwJ5klP65NDARDBuKZc4v+E5IGgz+/3GSXxKqg0Lxy77vgTHVqSUmtmiMnJowt+a
            5u6T7s4IHX8i/eANx9KyxIPoIylhuPuW1i9tiIO2HWJcAjcF8K4/f83l3DHKDVee
            66EcfD3TS/CSY45xJCoe6blF73yvuG0QHvvETdSgXmVyBkal+O5W++j8gZLB0YxX
            Ehj7vfvuQ8ZSWIBGluDYlbUcFufJN7xEomCcfvhVwGiZd/hTl5w2uYp3L6wSGo35
            4gh26FqQsvbqlT3MY9I7m6XMav586xESzzJWk+lQZecIpttqJI1/a8gngYeOSF/8
            Shq96ytMDQeaRfyOIYiSMyG+XMMEP3Vjo33sVwRiuDJUQMwWQY7h8Q7rCeroo0R+
            KkiX1YH45X+ERENZBanDWQOunHSXzV3rs67Kohew4Xg4Pp+SQmAaAPlwNyoy6PTr
            DrQG4ijU87Ea4WaVZxHY9s4dPYFh/D8hulqXEyitIXwg1h25zvPeFd/5v6Q8ONYB
            ubEM0A851lCWdEHctcuzK5q2cwcPQEYdQB6F6QBUW7j59yoh9C9zFEt14vNTbYbU
            aAEJAhBOYMNzb+9Ma5WISPpm1oyrp8CTj4zKPUS0k33wRaOLbmhkxjn4GkCZnHof
            uUZRKdtUd+ri6Qcun7P2dtW4Aort9jGJSPUK8hEAoAh/EXMKFxn86hXlxKAXNMed
            7Le7sbZcw1Ug
            =u1Hd
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-postgres-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:PFk+Or1uZID2,iv:pbcxzEHhp3kjxnk6noEwNb+V/QgeVZLTR9FmybAbmoE=,tag:c6c8n7VvrKOY7hhw8HCLew==,type:str]
    password: ENC[AES256_GCM,data:BkPQkRNrsEt1VjoEDNlvrXxawaH58aGi/iFa0b+E,iv:gv7GJW3XPBw0ybdVhXh8cvL7FY5ogEcd41Vb73mI+5A=,tag:Go/yWQtbpgcBgv7TiMloXA==,type:str]
sops:
    lastmodified: "2026-03-01T10:48:07Z"
    mac: ENC[AES256_GCM,data:+vgm2cTZN3eipcnKNKoDdZsB3fJfi/9ddbHI75y2vDPPeFP2KcBRrrFAAlej6c8lGqC1pNqW7c1peMLVZ1DZLlGoSVlq2zck2gc3F7gXFfBFMJKTThjGQ8tyvY1gc2ZqqFb5K3AIav3EchDJeEns8nfE+KwNfLKoFt3VRTZu1Xw=,iv:HMSyDZHzSg3tkroTCu8m+GdxIkiuPPRI/K2eYHYMtA8=,tag:IcQ4N1ynbhnbTHRfwSrfSw==,type:str]
    pgp:
        - created_at: "2026-03-01T10:48:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWAQ//TZ4oKy9W4uH93Vm1xZT8RkK9ZfvcRb3z0SXXAlbiqSvg
            /FOy9JBJEtOVLdN1CgYDqrX/UsnXWwf6bXJnQxjL9aFimElOOyIgrWF5pnR/T2KL
            xwJ5klP65NDARDBuKZc4v+E5IGgz+/3GSXxKqg0Lxy77vgTHVqSUmtmiMnJowt+a
            5u6T7s4IHX8i/eANx9KyxIPoIylhuPuW1i9tiIO2HWJcAjcF8K4/f83l3DHKDVee
            66EcfD3TS/CSY45xJCoe6blF73yvuG0QHvvETdSgXmVyBkal+O5W++j8gZLB0YxX
            Ehj7vfvuQ8ZSWIBGluDYlbUcFufJN7xEomCcfvhVwGiZd/hTl5w2uYp3L6wSGo35
            4gh26FqQsvbqlT3MY9I7m6XMav586xESzzJWk+lQZecIpttqJI1/a8gngYeOSF/8
            Shq96ytMDQeaRfyOIYiSMyG+XMMEP3Vjo33sVwRiuDJUQMwWQY7h8Q7rCeroo0R+
            KkiX1YH45X+ERENZBanDWQOunHSXzV3rs67Kohew4Xg4Pp+SQmAaAPlwNyoy6PTr
            DrQG4ijU87Ea4WaVZxHY9s4dPYFh/D8hulqXEyitIXwg1h25zvPeFd/5v6Q8ONYB
            ubEM0A851lCWdEHctcuzK5q2cwcPQEYdQB6F6QBUW7j59yoh9C9zFEt14vNTbYbU
            aAEJAhBOYMNzb+9Ma5WISPpm1oyrp8CTj4zKPUS0k33wRaOLbmhkxjn4GkCZnHof
            uUZRKdtUd+ri6Qcun7P2dtW4Aort9jGJSPUK8hEAoAh/EXMKFxn86hXlxKAXNMed
            7Le7sbZcw1Ug
            =u1Hd
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: beanstash-staging-basic-auth
type: Opaque
# htpasswd format: user:$apr1$...
stringData:
    users: ENC[AES256_GCM,data:PBlTH5fPbHagT3TTxefOVG/uZWyIi3bU/tmt76cXqbPtblChQF+RpSiCidw9+pY=,iv:V3Q5avTRAdFTVIEgzEuKqcVwdrSoNJGxSLBItIkqniM=,tag:8c6VF4shOkw2xl/UTcPrYw==,type:str]
sops:
    lastmodified: "2026-03-01T10:48:07Z"
    mac: ENC[AES256_GCM,data:+vgm2cTZN3eipcnKNKoDdZsB3fJfi/9ddbHI75y2vDPPeFP2KcBRrrFAAlej6c8lGqC1pNqW7c1peMLVZ1DZLlGoSVlq2zck2gc3F7gXFfBFMJKTThjGQ8tyvY1gc2ZqqFb5K3AIav3EchDJeEns8nfE+KwNfLKoFt3VRTZu1Xw=,iv:HMSyDZHzSg3tkroTCu8m+GdxIkiuPPRI/K2eYHYMtA8=,tag:IcQ4N1ynbhnbTHRfwSrfSw==,type:str]
    pgp:
        - created_at: "2026-03-01T10:48:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/cF29oNCPyWAQ//TZ4oKy9W4uH93Vm1xZT8RkK9ZfvcRb3z0SXXAlbiqSvg
            /FOy9JBJEtOVLdN1CgYDqrX/UsnXWwf6bXJnQxjL9aFimElOOyIgrWF5pnR/T2KL
            xwJ5klP65NDARDBuKZc4v+E5IGgz+/3GSXxKqg0Lxy77vgTHVqSUmtmiMnJowt+a
            5u6T7s4IHX8i/eANx9KyxIPoIylhuPuW1i9tiIO2HWJcAjcF8K4/f83l3DHKDVee
            66EcfD3TS/CSY45xJCoe6blF73yvuG0QHvvETdSgXmVyBkal+O5W++j8gZLB0YxX
            Ehj7vfvuQ8ZSWIBGluDYlbUcFufJN7xEomCcfvhVwGiZd/hTl5w2uYp3L6wSGo35
            4gh26FqQsvbqlT3MY9I7m6XMav586xESzzJWk+lQZecIpttqJI1/a8gngYeOSF/8
            Shq96ytMDQeaRfyOIYiSMyG+XMMEP3Vjo33sVwRiuDJUQMwWQY7h8Q7rCeroo0R+
            KkiX1YH45X+ERENZBanDWQOunHSXzV3rs67Kohew4Xg4Pp+SQmAaAPlwNyoy6PTr
            DrQG4ijU87Ea4WaVZxHY9s4dPYFh/D8hulqXEyitIXwg1h25zvPeFd/5v6Q8ONYB
            ubEM0A851lCWdEHctcuzK5q2cwcPQEYdQB6F6QBUW7j59yoh9C9zFEt14vNTbYbU
            aAEJAhBOYMNzb+9Ma5WISPpm1oyrp8CTj4zKPUS0k33wRaOLbmhkxjn4GkCZnHof
            uUZRKdtUd+ri6Qcun7P2dtW4Aort9jGJSPUK8hEAoAh/EXMKFxn86hXlxKAXNMed
            7Le7sbZcw1Ug
            =u1Hd
            -----END PGP MESSAGE-----
          fp: 05F6A512DD349B0E33C7F417CBB5F307693F111D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
